require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserInformationsController do

  # This should return the minimal set of attributes required to create a valid
  # UserInformation. As you add validations to UserInformation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserInformationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all user_informations as @user_informations" do
      user_information = UserInformation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_informations).should eq([user_information])
    end
  end

  describe "GET show" do
    it "assigns the requested user_information as @user_information" do
      user_information = UserInformation.create! valid_attributes
      get :show, {:id => user_information.to_param}, valid_session
      assigns(:user_information).should eq(user_information)
    end
  end

  describe "GET new" do
    it "assigns a new user_information as @user_information" do
      get :new, {}, valid_session
      assigns(:user_information).should be_a_new(UserInformation)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_information as @user_information" do
      user_information = UserInformation.create! valid_attributes
      get :edit, {:id => user_information.to_param}, valid_session
      assigns(:user_information).should eq(user_information)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserInformation" do
        expect {
          post :create, {:user_information => valid_attributes}, valid_session
        }.to change(UserInformation, :count).by(1)
      end

      it "assigns a newly created user_information as @user_information" do
        post :create, {:user_information => valid_attributes}, valid_session
        assigns(:user_information).should be_a(UserInformation)
        assigns(:user_information).should be_persisted
      end

      it "redirects to the created user_information" do
        post :create, {:user_information => valid_attributes}, valid_session
        response.should redirect_to(UserInformation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_information as @user_information" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserInformation.any_instance.stub(:save).and_return(false)
        post :create, {:user_information => {}}, valid_session
        assigns(:user_information).should be_a_new(UserInformation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserInformation.any_instance.stub(:save).and_return(false)
        post :create, {:user_information => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_information" do
        user_information = UserInformation.create! valid_attributes
        # Assuming there are no other user_informations in the database, this
        # specifies that the UserInformation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserInformation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => user_information.to_param, :user_information => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested user_information as @user_information" do
        user_information = UserInformation.create! valid_attributes
        put :update, {:id => user_information.to_param, :user_information => valid_attributes}, valid_session
        assigns(:user_information).should eq(user_information)
      end

      it "redirects to the user_information" do
        user_information = UserInformation.create! valid_attributes
        put :update, {:id => user_information.to_param, :user_information => valid_attributes}, valid_session
        response.should redirect_to(user_information)
      end
    end

    describe "with invalid params" do
      it "assigns the user_information as @user_information" do
        user_information = UserInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserInformation.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_information.to_param, :user_information => {}}, valid_session
        assigns(:user_information).should eq(user_information)
      end

      it "re-renders the 'edit' template" do
        user_information = UserInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserInformation.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_information.to_param, :user_information => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_information" do
      user_information = UserInformation.create! valid_attributes
      expect {
        delete :destroy, {:id => user_information.to_param}, valid_session
      }.to change(UserInformation, :count).by(-1)
    end

    it "redirects to the user_informations list" do
      user_information = UserInformation.create! valid_attributes
      delete :destroy, {:id => user_information.to_param}, valid_session
      response.should redirect_to(user_informations_url)
    end
  end

end
